services:
  app: 
    build: .
    container_name: dailytrends
    ports: 
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${DB_URI}
    volumes:
      - .:/usr/src/app
    command: npm run start

  mongo: 
    image: mongo:latest
    container_name: dailytrends-mongo
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: